testingstructs :
	gcc headers/eror_handling/eror_handling.c	utilities/initialize/initialize.c utilities/structutils/struct-utils.c headers/utilities/utilities.c utilities/configs/configparse.c Locker.c -I utilities/initialize -I utilities/structutils -I headers/eror_handling -o testinginitialize -I headers/utilities  -I utilities/configs/ -I headers/defined_values/

optimization_testing :
	gcc -O3 headers/eror_handling/eror_handling.c	utilities/initialize/initialize.c utilities/structutils/struct-utils.c headers/utilities/utilities.c utilities/configs/configparse.c Locker.c -I utilities/initialize -I utilities/structutils -I headers/eror_handling -o testinginitialize -I headers/utilities  -I utilities/configs/ -I headers/defined_values/

debug :
	gcc -g headers/eror_handling/eror_handling.c	utilities/initialize/initialize.c utilities/structutils/struct-utils.c headers/utilities/utilities.c utilities/configs/configparse.c Locker.c -I utilities/initialize -I utilities/structutils -I headers/eror_handling -o testinginitialize -I headers/utilities  -I utilities/configs/ -I headers/defined_values/


